# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache
org.gradle.configuration-cache=false

# Fabric Properties
minecraft_version=26.1.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
version=2.0.3
group=com.momocraft.textfilter

# Dependencies
fabric_api_version=0.155.2+26.1.2